/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apresentacao;

import entidade.TitulosPagar;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import negocio.NTitulosPagar;

/**
 *
 * @author diogo
 */
public class FrmPesTitulosPagar extends javax.swing.JInternalFrame {

    JDesktopPane pnlPrincipal;

    /**
     * Creates new form FrmPesTitulosPagar
     */
    public FrmPesTitulosPagar() {
        initComponents();
        carregarTabela();
    }

    public FrmPesTitulosPagar(JDesktopPane pnlPrincipal) {
        this();
        this.pnlPrincipal = pnlPrincipal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblResultado = new javax.swing.JTable();
        btnFechar = new javax.swing.JButton();

        tblResultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblResultado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblResultadoMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblResultado);

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 774, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFechar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(btnFechar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblResultadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblResultadoMousePressed
        try {
            int linha = tblResultado.getSelectedRow();
            String codigo = tblResultado.getValueAt(linha, 0).toString();

            FrmCadTitulosPagar janela = new FrmCadTitulosPagar(pnlPrincipal, codigo);
            pnlPrincipal.add(janela);

            janela.setVisible(true);
            this.dispose();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_tblResultadoMousePressed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void carregarTabela() {
        try {
            Vector<String> cabecalho = new Vector();
            cabecalho.add("Código");
            cabecalho.add("Fornecedor");
            cabecalho.add("Centro de Custo");
            cabecalho.add("Data de Cadastro");
            cabecalho.add("Data Vencimento");
            cabecalho.add("Valor");
            cabecalho.add("Juros");
            cabecalho.add("Desconto");
            cabecalho.add("Situacao");

            NTitulosPagar negocio = new NTitulosPagar();
            Vector linhas = new Vector();

            for (TitulosPagar tp : negocio.listar()) {

                Vector<String> detalhe = new Vector();
                String status = (tp.getSituacao().equals("A") ? "Aberto" : "Baixado");
                
                detalhe.add(tp.getId() + "");
                detalhe.add(tp.getFornecedor().getNome()+ "");
                detalhe.add(tp.getCentroCusto().getDescricao()+ "");
                detalhe.add(tp.getDataCadastro());
                detalhe.add(tp.getDataVencimento());                
                detalhe.add(String.valueOf(tp.getValor()));
                detalhe.add(String.valueOf(tp.getJuros()));
                detalhe.add(String.valueOf(tp.getDesconto()));
                detalhe.add(status);

                linhas.add(detalhe);

            }
            tblResultado.setModel(new DefaultTableModel(linhas, cabecalho));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFechar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblResultado;
    // End of variables declaration//GEN-END:variables
}
